### ISSUE TITLE
[Код] Потерянный астероид+Поле астероидов

### ISSUE THREAD

**Issue by ai-ry** [ai-ry/orbit#13]
Есть 3 цвета потерянных астероидов: красные, зеленые и синие.
Подбираются игроком и начинают вращаться вокруг него.
![image](https://cloud.githubusercontent.com/assets/13381202/9839017/999ae304-5a75-11e5-837c-6128ee537ae1.png)

Для астероидов есть их поля астероидов. Подобранный игроком астероид нужно доставить в поле его цвета. Т.е., если игрок подобрал красный астероид - доставить в красное поле, если зеленый - в зеленое, если синий - в синее.

За все доставленные на поле игры потерянные астероиды игрок получает звезду за исполнение.

**Comment by i9deity** [comment]
пока займусь потерянными астероидами.

**Comment by ai-ry** [comment]
13ая таска, счастливый номер выбрал?)
