### ISSUE TITLE
[Дизайн] Создать макет главного меню

### ISSUE THREAD

**Issue by ai-ry** [ai-ry/orbit#38]
Макет главного меню. Составляющие:
- Созвездия, представляющие собой соединенные в цепочки уровни-звезды.
- Кнопка "Настройки"
- Кнопка "Достижения"
- Детали миссии уровня (поп-ап панель, выскакивающая когда игрок выбирает уровень из созвездия). Содержит: список условий миссии, кнопки "Начать уровень", "Возврат". Можно сделать несколько вариантов (например без кнопки "Возврат"), чтобы выбрать как лучше.
- Достижения (поп-ап панель, выскакивающая при нажатии кнопки Достижения). Содержит: список достижений игрока, кнопку возврата.

**Comment by i9deity** [comment]
Сява, как у тебя там с макетом меню?

**Comment by namesake08** [comment]
меню готово, всплывающие окна еще нет.
